maternity: 0.07
faker:
  locale:
    - en_US  # English (United States)
    - es_MX  # Spanish (Mexico)
    - hr     # Croatian                 ---- https://faker.readthedocs.io/en/master/locales.html
filter_icd_prefix: #prefix of ICD codes that won't be included in EHRs
  - A0
  - E10
result_format: 'JSON' #XML;JSON; turtle; rdf/xml; json-ld
